#ifndef SBDEF_NAME_ALIAS
#error "should define SBDEF_NAME_ALIAS( code_point, name, alias, tag )"
#endif


SBDEF_NAME_ALIAS( 0x0000, NULL, Null, control )
SBDEF_NAME_ALIAS( 0x0000, NUL, Nul, abbreviation )
SBDEF_NAME_ALIAS( 0x0001, START OF HEADING, Start_Of_Heading, control )
SBDEF_NAME_ALIAS( 0x0001, SOH, Soh, abbreviation )
SBDEF_NAME_ALIAS( 0x0002, START OF TEXT, Start_Of_Text, control )
SBDEF_NAME_ALIAS( 0x0002, STX, Stx, abbreviation )
SBDEF_NAME_ALIAS( 0x0003, END OF TEXT, End_Of_Text, control )
SBDEF_NAME_ALIAS( 0x0003, ETX, Etx, abbreviation )
SBDEF_NAME_ALIAS( 0x0004, END OF TRANSMISSION, End_Of_Transmission, control )
SBDEF_NAME_ALIAS( 0x0004, EOT, Eot, abbreviation )
SBDEF_NAME_ALIAS( 0x0005, ENQUIRY, Enquiry, control )
SBDEF_NAME_ALIAS( 0x0005, ENQ, Enq, abbreviation )
SBDEF_NAME_ALIAS( 0x0006, ACKNOWLEDGE, Acknowledge, control )
SBDEF_NAME_ALIAS( 0x0006, ACK, Ack, abbreviation )

// Note that no formal name alias for the ISO 6429 "BELL" is
// provided for U+0007, because of the existing name collision
// with U+1F514 BELL.

SBDEF_NAME_ALIAS( 0x0007, ALERT, Alert, control )
SBDEF_NAME_ALIAS( 0x0007, BEL, Bel, abbreviation )

SBDEF_NAME_ALIAS( 0x0008, BACKSPACE, Backspace, control )
SBDEF_NAME_ALIAS( 0x0008, BS, Bs, abbreviation )
SBDEF_NAME_ALIAS( 0x0009, CHARACTER TABULATION, Character_Tabulation, control )
SBDEF_NAME_ALIAS( 0x0009, HORIZONTAL TABULATION, Horizontal_Tabulation, control )
SBDEF_NAME_ALIAS( 0x0009, HT, Ht, abbreviation )
SBDEF_NAME_ALIAS( 0x0009, TAB, Tab, abbreviation )
SBDEF_NAME_ALIAS( 0x000a, LINE FEED, Line_Feed, control )
SBDEF_NAME_ALIAS( 0x000a, NEW LINE, New_Line, control )
SBDEF_NAME_ALIAS( 0x000a, END OF LINE, End_Of_Line, control )
SBDEF_NAME_ALIAS( 0x000a, LF, Lf, abbreviation )
SBDEF_NAME_ALIAS( 0x000a, NL, Nl, abbreviation )
SBDEF_NAME_ALIAS( 0x000a, EOL, Eol, abbreviation )
SBDEF_NAME_ALIAS( 0x000b, LINE TABULATION, Line_Tabulation, control )
SBDEF_NAME_ALIAS( 0x000b, VERTICAL TABULATION, Vertical_Tabulation, control )
SBDEF_NAME_ALIAS( 0x000b, VT, Vt, abbreviation )
SBDEF_NAME_ALIAS( 0x000c, FORM FEED, Form_Feed, control )
SBDEF_NAME_ALIAS( 0x000c, FF, Ff, abbreviation )
SBDEF_NAME_ALIAS( 0x000d, CARRIAGE RETURN, Carriage_Return, control )
SBDEF_NAME_ALIAS( 0x000d, CR, Cr, abbreviation )
SBDEF_NAME_ALIAS( 0x000e, SHIFT OUT, Shift_Out, control )
SBDEF_NAME_ALIAS( 0x000e, LOCKING-SHIFT ONE, LockingShift_One, control )
SBDEF_NAME_ALIAS( 0x000e, SO, So, abbreviation )
SBDEF_NAME_ALIAS( 0x000f, SHIFT IN, Shift_In, control )
SBDEF_NAME_ALIAS( 0x000f, LOCKING-SHIFT ZERO, LockingShift_Zero, control )
SBDEF_NAME_ALIAS( 0x000f, SI, Si, abbreviation )
SBDEF_NAME_ALIAS( 0x0010, DATA LINK ESCAPE, Data_Link_Escape, control )
SBDEF_NAME_ALIAS( 0x0010, DLE, Dle, abbreviation )
SBDEF_NAME_ALIAS( 0x0011, DEVICE CONTROL ONE, Device_Control_One, control )
SBDEF_NAME_ALIAS( 0x0011, DC1, Dc1, abbreviation )
SBDEF_NAME_ALIAS( 0x0012, DEVICE CONTROL TWO, Device_Control_Two, control )
SBDEF_NAME_ALIAS( 0x0012, DC2, Dc2, abbreviation )
SBDEF_NAME_ALIAS( 0x0013, DEVICE CONTROL THREE, Device_Control_Three, control )
SBDEF_NAME_ALIAS( 0x0013, DC3, Dc3, abbreviation )
SBDEF_NAME_ALIAS( 0x0014, DEVICE CONTROL FOUR, Device_Control_Four, control )
SBDEF_NAME_ALIAS( 0x0014, DC4, Dc4, abbreviation )
SBDEF_NAME_ALIAS( 0x0015, NEGATIVE ACKNOWLEDGE, Negative_Acknowledge, control )
SBDEF_NAME_ALIAS( 0x0015, NAK, Nak, abbreviation )
SBDEF_NAME_ALIAS( 0x0016, SYNCHRONOUS IDLE, Synchronous_Idle, control )
SBDEF_NAME_ALIAS( 0x0016, SYN, Syn, abbreviation )
SBDEF_NAME_ALIAS( 0x0017, END OF TRANSMISSION BLOCK, End_Of_Transmission_Block, control )
SBDEF_NAME_ALIAS( 0x0017, ETB, Etb, abbreviation )
SBDEF_NAME_ALIAS( 0x0018, CANCEL, Cancel, control )
SBDEF_NAME_ALIAS( 0x0018, CAN, Can, abbreviation )
SBDEF_NAME_ALIAS( 0x0019, END OF MEDIUM, End_Of_Medium, control )
SBDEF_NAME_ALIAS( 0x0019, EOM, Eom, abbreviation )
SBDEF_NAME_ALIAS( 0x001a, SUBSTITUTE, Substitute, control )
SBDEF_NAME_ALIAS( 0x001a, SUB, Sub, abbreviation )
SBDEF_NAME_ALIAS( 0x001b, ESCAPE, Escape, control )
SBDEF_NAME_ALIAS( 0x001b, ESC, Esc, abbreviation )
SBDEF_NAME_ALIAS( 0x001c, INFORMATION SEPARATOR FOUR, Information_Separator_Four, control )
SBDEF_NAME_ALIAS( 0x001c, FILE SEPARATOR, File_Separator, control )
SBDEF_NAME_ALIAS( 0x001c, FS, Fs, abbreviation )
SBDEF_NAME_ALIAS( 0x001d, INFORMATION SEPARATOR THREE, Information_Separator_Three, control )
SBDEF_NAME_ALIAS( 0x001d, GROUP SEPARATOR, Group_Separator, control )
SBDEF_NAME_ALIAS( 0x001d, GS, Gs, abbreviation )
SBDEF_NAME_ALIAS( 0x001e, INFORMATION SEPARATOR TWO, Information_Separator_Two, control )
SBDEF_NAME_ALIAS( 0x001e, RECORD SEPARATOR, Record_Separator, control )
SBDEF_NAME_ALIAS( 0x001e, RS, Rs, abbreviation )
SBDEF_NAME_ALIAS( 0x001f, INFORMATION SEPARATOR ONE, Information_Separator_One, control )
SBDEF_NAME_ALIAS( 0x001f, UNIT SEPARATOR, Unit_Separator, control )
SBDEF_NAME_ALIAS( 0x001f, US, Us, abbreviation )
SBDEF_NAME_ALIAS( 0x0020, SP, Sp, abbreviation )
SBDEF_NAME_ALIAS( 0x007f, DELETE, Delete, control )
SBDEF_NAME_ALIAS( 0x007f, DEL, Del, abbreviation )

#undef SBDEF_NAME_ALIAS
